name = "ReSolverChannelFlow"
uuid = "ea847659-7271-4841-b0fc-79dd10df6815"
version = "0.1.0"
authors = ["Thomas Burton <tburton5572@gmail.com>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NSEBase = "9778a910-ce4d-423e-92be-12991f0cf10c"

[sources]
NSEBase = {path = "/home/tpb1y19/Code/NSEBase.jl/"}

[compat]
JLD2 = "0.6.3"
LinearAlgebra = "1.11.0"
