name = "OpenChannelFlow"
uuid = "ea847659-7271-4841-b0fc-79dd10df6815"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"

[extras]
ChebUtils = "5c307136-fb89-411d-b568-fbf16049e5ad"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ChebUtils", "LinearAlgebra"]
