name = "RPCF"
uuid = "ea847659-7271-4841-b0fc-79dd10df6815"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ReSolverInterface = "9a172a43-bfaf-4cc4-8edb-b32fc4c49da3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
